### ISSUE TITLE
Should not fire when mouse moves more than margin

### ISSUE THREAD

**Issue by allenhwkim** [john-doherty/long-press#2]
Hi,

Thanks for this code.
However, IMHO, when mouse pressed and moved a lot, it should not be considered and 'long-press', but as considered as 'drag'.

I am trying to implement your code on my mobile solution, http://plnkr.co/edit/B3xgDpGdafD4AoI3KFyo?p=preview, but it seems not suitable when it goes with your long-press.

I also would appreciate your feedback.

**Comment by john-doherty** [comment]
Hi @allenhwkim, the `long-press` handler is monitoring the **mouseout** event, as soon as the mouse/touch leaves the element that triggered it - the timer is canceled. 

So it does not fire when the mouse/touch moves.... Unless I'm missing something?

**Comment by john-doherty** [comment]
@allenhwkim you're canceling the **touchstart** event on line 84. Which means the 'long-press' event will never get started.

```
el.addEventListener('touchstart', e => e.preventDefault());
```

**Comment by allenhwkim** [comment]
Thanks, I may reconsider line 84.

Let's talk without touch event.

What I think is `mousedown and mousedown` is a `long-press`. However,  `mousedown then mousemove` is not a `long-press`, but `drag`(which you don't have at the moment).

In your example, mousedown, then move around, I still see the `long-press` is fired, which I think it should not.
Let's talk without touch event.

What I think is `mousedown and mousedown` is a `long-press`. However,  `mousedown then mousemove` is not a `long-press`, but `drag`(which you don't have at the moment).

In your example, mousedown, then move around, I still see the `long-press` is fired, which I think it should not.

**Comment by john-doherty** [comment]
If the user mouses down, but then moves, the long-press should be canceled. The long-press event should only fire if the user holds down the mouse _(or touch)_, in one fixed location for 1500ms. 

Pleas can you add a [plnkr.co](http://plnkr.co) or [jsfiddle](http://jsfiddle.net) that demonstrates the issue you are having?

**Comment by allenhwkim** [comment]
With your example, https://jsfiddle.net/5xrtx69z/1/, on the box, if you mousedown on the top-left corner, then move mouse to the bottom-right corder, the event still fires. What I think it it should not fire the event, because mouse has been moved a lot.

**Comment by john-doherty** [comment]
Good find @allenhwkim, I've checked in a fix. The solution was to cancel the long-press timer when the mouse/touch moves.
