### ISSUE TITLE
Issue with mouse moving on Scroll window

### ISSUE THREAD

**Issue by cablegunmaster** [john-doherty/long-press#4]
Thanks for writing the library in advance +1

**Explanation of bug:**
1. When I drag the scroll bar of an element,  where the long click event is binded to it does not fire the cancel event and registers as a "long-click" event, and fires the function attached.
2. When the mouse is clicked, and moved at the same time it fires the event, instead of cancelling it.

I am guessing this is because its the same element, or scrolling is counted as a different event as a mouse move event?

I was thinking about something like below, but its not yet the solution,and i'm feeling like i'm on the right track, but not there yet.
```
// clear if the mouse scrolls
document.addEventListener("scroll", function(e) {
    clearTimeout(timer);
});
```

**Comment by john-doherty** [comment]
Sorry I missed this @cablegunmaster, did you manage to resolve the issue?

**Comment by cablegunmaster** [comment]
not yet, it still fires when scrolling. 
Should be something like: "When click happens and scrolling event fires too interrupt/stop longclick event" 
but i am not getting it implemented correctly.

**Comment by cablegunmaster** [comment]
Issue not yet closed; to fully fix this I might have to add scroll event as well.
Why? just using "wheel" might not work on every Browser:
https://www.quirksmode.org/dom/events/scroll.html

Also see the test page and use some diff browser to test this issue on:
https://www.quirksmode.org/dom/events/tests/scroll.html

Hopefully this might explain why, have to add a better pull request.

**Comment by cablegunmaster** [comment]
Added all possible Scroll/ Mousewheel/ Wheel events to the Library, so it can accomodate "Long-press" but also STOP if the user scrolls.

A scroll/ mouse dragging event is not a Long-press event.
